
all: run

run:
	python src/predict_params.py

parametric:
	python src/parametric.py
	
learn:
	python src/line_prediction_mini.py

draw:
	python src/draw.py
	
output-clean:
	rm -rf output

model-clean:
	rm -rf model
	
cache-clean:
	rm -rf cache
	

run-temp:
	python temp.py
