
all: run

run-temp:
	python temp.py
	
learn:
	python src/line_prediction_mini.py

run:
	python src/main2.py
	
clean:
	rm -rf output

model-clean:
	rm -rf model
	
cache-clean:
	rm -rf cache

line:
	python src/line_prediction_mini.py
